server:
  port: 8083
spring:
  application:
    name: rating-service
  config:
    import: configserver:http://localhost:8086
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      host: localhost
      database: ratingservice
      # picked up from config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka




